import 'package:flutter_application_1/features/profile/domain/entites/profile_entity.dart';
import 'package:json_annotation/json_annotation.dart';

part 'profile_api_model.g.dart';

@JsonSerializable()
class ProfileApiModel {
  @JsonKey(name: '_id')
  final String? id; // usually the studentId / user id

  final String? profilePicture; // URL string or null

  // If backend sometimes sends these (optional – add only if your API actually returns them)
  // final String? name;
  // final String? email;
  // final String? phone;
  // final String? department;
  // final int? batchYear;
  // final List<String>? reportedItemIds;   // or List<ItemApiModel> if nested

  ProfileApiModel({
    this.id,
    this.profilePicture,
    // Add other fields here if they exist in your real API response
  });

  // ──────────────────────────────────────────────
  // JSON serialization (generated by json_serializable)
  // ──────────────────────────────────────────────

  factory ProfileApiModel.fromJson(Map<String, dynamic> json) =>
      _$ProfileApiModelFromJson(json);

  Map<String, dynamic> toJson() => _$ProfileApiModelToJson(this);

  // ──────────────────────────────────────────────
  // Domain entity conversion
  // ──────────────────────────────────────────────

  ProfileEntity toEntity() {
    return ProfileEntity(
      studentId: id ?? '', // ← most important: backend _id → studentId
      profilePicture: profilePicture,
    );
  }

  factory ProfileApiModel.fromEntity(ProfileEntity entity) {
    return ProfileApiModel(
      id: entity.studentId,
      profilePicture: entity.profilePicture,
    );
  }

  // Convenience method – if you ever receive list of profiles
  static List<ProfileEntity> toEntityList(List<ProfileApiModel> models) {
    return models.map((model) => model.toEntity()).toList();
  }
}
