// File: lib/features/auth/data/models/auth_hive_model.dart

import 'package:flutter_application_1/core/constants/hive_table_constatn.dart';
import 'package:flutter_application_1/features/auth/domain/entities/auth_entity.dart';
import 'package:hive/hive.dart';
import 'package:uuid/uuid.dart';

part 'auth_hive_model.g.dart'; // Generated by build_runner

@HiveType(typeId: HiveTableConstant.authTypeId)
class AuthHiveModel extends HiveObject {
  @HiveField(0)
  final String authId; // Made non-nullable — always generated

  @HiveField(1)
  final String fullName;

  @HiveField(2)
  final String email;

  @HiveField(3)
  final String? phoneNumber;

  @HiveField(4)
  final String? batchId;

  @HiveField(5)
  final String userName;

  @HiveField(6)
  final String? password; // Keep nullable — cleared on logout if needed

  @HiveField(7)
  final String? profilePicture;

  AuthHiveModel({
    String? authId,
    required this.fullName,
    required this.email,
    this.phoneNumber,
    this.batchId,
    required this.userName,
    this.password,
    this.profilePicture,
  }) : authId = authId ?? const Uuid().v4();

  // Factory from domain entity
  factory AuthHiveModel.fromEntity(AuthEntity entity) {
    return AuthHiveModel(
      authId: entity.userId ?? const Uuid().v4(),
      fullName: entity.fullName ?? '',
      email: entity.email ?? '',
      phoneNumber: entity.phoneNumber,
      batchId: entity.batchId,
      userName: entity.username ?? '',
      password: entity.password,
      profilePicture: entity.profilePicture,
    );
  }

  // Convert to domain entity
  AuthEntity toEntity() {
    return AuthEntity(
      userId: authId,
      fullName: fullName,
      email: email,
      phoneNumber: phoneNumber,
      // batchId: batchId,
      username: userName,
      password: password,
      profilePicture: profilePicture,
      batchId: '',
    );
  }

  // Optional: Enhanced version with batch entity if needed later
  // AuthEntity toEntity({BatchEntity? batchEntity}) {
  //   return AuthEntity(
  //     userId: authId,
  //     fullName: fullName,
  //     email: email,
  //     phoneNumber: phoneNumber,
  //     batchId: batchId,
  //     username: userName,
  //     password: password,
  //     profilePicture: profilePicture,
  //     batch: batchEntity,
  //   );
  // }

  // List conversion
  static List<AuthEntity> toEntityList(List<AuthHiveModel> models) {
    return models.map((model) => model.toEntity()).toList();
  }

  // Essential: copyWith method for safe updates
  AuthHiveModel copyWith({
    String? authId,
    String? fullName,
    String? email,
    String? phoneNumber,
    String? batchId,
    String? userName,
    String? password,
    String? profilePicture,
  }) {
    return AuthHiveModel(
      authId: authId ?? this.authId,
      fullName: fullName ?? this.fullName,
      email: email ?? this.email,
      phoneNumber: phoneNumber ?? this.phoneNumber,
      batchId: batchId ?? this.batchId,
      userName: userName ?? this.userName,
      password: password ?? this.password,
      profilePicture: profilePicture ?? this.profilePicture,
    );
  }

  @override
  String toString() {
    return 'AuthHiveModel(authId: $authId, fullName: $fullName, email: $email, userName: $userName)';
  }
}
